#! /bin/sh /usr/share/dpatch/dpatch-run
## hp-sendfax_crash_on_cancel.dpatch by  <till.kamppeter@gmail.com>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: No description.

@DPATCH@
diff -urNad hplip-2.8.4~/ui/scrollfax.py hplip-2.8.4/ui/scrollfax.py
--- hplip-2.8.4~/ui/scrollfax.py	2008-04-03 00:18:41.000000000 +0200
+++ hplip-2.8.4/ui/scrollfax.py	2008-04-04 09:26:49.000000000 +0200
@@ -1239,11 +1239,11 @@
 
                 if status  == fax.STATUS_ERROR:
                     self.form.FailureUI(self.__tr("<b>Fax send error.</b><p>"))
-                    self.dev.sendEvent(EVENT_FAX_JOB_FAIL, self.cur_printer, EVENT_FAX_JOB_FAIL, 0, '')
+                    self.dev.sendEvent(EVENT_FAX_JOB_FAIL, self.cur_printer, 0, '')
 
                 elif status == fax.STATUS_BUSY:
                     self.form.FailureUI(self.__tr("<b>Fax device is busy.</b><p>Please try again later."))
-                    self.dev.sendEvent(EVENT_FAX_JOB_FAIL, self.cur_printer, EVENT_FAX_JOB_FAIL, 0, '')
+                    self.dev.sendEvent(EVENT_FAX_JOB_FAIL, self.cur_printer, 0, '')
 
                 elif status == fax.STATUS_COMPLETED:
                     self.dev.sendEvent(EVENT_END_FAX_JOB, self.cur_printer, 0, '')
